# -*- coding: utf-8 -*-
"""mpl_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xkBvZWrGWRsgWJNDWl3_bsj0z3iLccy
"""

# Self-Pruning Neural Network on CIFAR-10
# Implements: PrunableLinear with learnable gate mechanism


import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as T
from torch.utils.data import DataLoader

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {DEVICE}")

# Hyperparameters for gating
SCALE = 6        # Controls sharpness of sigmoid
THRESH = 0.01    # Threshold to consider gate as zero (for sparsity calculation)

# Part 1: Prunable Linear Layer

class PrunableLinear(nn.Module):
    """
    Custom Linear Layer with learnable gates.
    Each weight has an associated gate (0–1) controlling its importance.
    """
    def __init__(self, in_features, out_features):
        super().__init__()

        # Standard weight and bias
        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))

        # Learnable gate scores (same shape as weights)
        self.gate_scores = nn.Parameter(torch.zeros(out_features, in_features))

    def forward(self, x):
        # Convert gate scores → (0,1) using sigmoid
        gates = torch.sigmoid(self.gate_scores * SCALE)

        # Hard pruning (optional but improves sparsity stability)
        gates = torch.where(gates < THRESH, torch.zeros_like(gates), gates)

        # Apply gating to weights
        pruned_weights = self.weight * gates

        # Standard linear transformation
        return F.linear(x, pruned_weights, self.bias)

    def gate_values(self):
        """Returns gate values for analysis/visualization"""
        with torch.no_grad():
            return torch.sigmoid(self.gate_scores * SCALE)

# Model Definition (MLP with Prunable Layers)

class SparseMLP(nn.Module):
    def __init__(self):
        super().__init__()

        self.l1 = PrunableLinear(3072, 800)
        self.l2 = PrunableLinear(800, 400)
        self.l3 = PrunableLinear(400, 200)
        self.l4 = PrunableLinear(200, 10)

        self.bn1 = nn.BatchNorm1d(800)
        self.bn2 = nn.BatchNorm1d(400)
        self.bn3 = nn.BatchNorm1d(200)

    def forward(self, x):
        x = x.view(x.size(0), -1)

        x = F.relu(self.bn1(self.l1(x)))
        x = F.relu(self.bn2(self.l2(x)))
        x = F.relu(self.bn3(self.l3(x)))

        return self.l4(x)

    # Part 2: Sparsity Regularization (L1 on gates)

    def sparsity_loss(self):
        """
        L1 penalty on gate values to encourage sparsity
        """
        total = 0
        for m in self.modules():
            if isinstance(m, PrunableLinear):
                total += torch.sum(torch.sigmoid(m.gate_scores * SCALE))
        return total

    def sparsity_ratio(self):
        """
        Computes % of pruned weights (gates near zero)
        """
        total = zero = 0
        for m in self.modules():
            if isinstance(m, PrunableLinear):
                g = torch.sigmoid(m.gate_scores * SCALE)
                total += g.numel()
                zero += (g < THRESH).sum().item()
        return zero / total

    def all_gate_values(self):
        """Collect all gate values for plotting"""
        parts = []
        for m in self.modules():
            if isinstance(m, PrunableLinear):
                parts.append(m.gate_values().cpu().numpy().ravel())
        return np.concatenate(parts)

# Data Loading (CIFAR-10)

def load_data(batch_size=256):
    mean = (0.4914, 0.4822, 0.4465)
    std  = (0.2470, 0.2435, 0.2616)

    train_tf = T.Compose([
        T.RandomHorizontalFlip(),
        T.RandomCrop(32, padding=4),
        T.ToTensor(),
        T.Normalize(mean, std),
    ])

    test_tf = T.Compose([
        T.ToTensor(),
        T.Normalize(mean, std),
    ])

    train_ds = torchvision.datasets.CIFAR10(
        "./data", train=True, download=True, transform=train_tf)

    test_ds = torchvision.datasets.CIFAR10(
        "./data", train=False, download=True, transform=test_tf)

    return (
        DataLoader(train_ds, batch_size=batch_size, shuffle=True),
        DataLoader(test_ds, batch_size=batch_size, shuffle=False),
    )

# Training Loop

def train_epoch(model, loader, optimizer, lam, ep, epochs):
    model.train()

    total_loss = correct = total = 0

    # Lambda warm-up (gradually increase sparsity pressure)
    lam_t = lam * (ep / epochs)

    for x, y in loader:
        x, y = x.to(DEVICE), y.to(DEVICE)

        optimizer.zero_grad()

        outputs = model(x)

        # Total Loss = Classification + Sparsity
        loss = F.cross_entropy(outputs, y) + lam_t * model.sparsity_loss()

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        correct += (outputs.argmax(1) == y).sum().item()
        total += y.size(0)

    return total_loss / len(loader), correct / total

# Evaluation

@torch.no_grad()
def evaluate(model, loader):
    model.eval()

    correct = total = 0
    for x, y in loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        preds = model(x).argmax(1)
        correct += (preds == y).sum().item()
        total += y.size(0)

    return correct / total

# Plot Gate Distributions

def plot_distributions(results):
    fig, axes = plt.subplots(1, len(results), figsize=(6 * len(results), 4))

    for ax, res in zip(axes, results):
        ax.hist(res["gates"], bins=80, range=(0, 1), alpha=0.8)
        ax.axvline(THRESH, linestyle="--", label="threshold")

        ax.set_title(
            f"λ={res['lam']:.0e}\nAcc={res['acc']*100:.1f}% | Sparsity={res['sparsity']*100:.1f}%"
        )
        ax.set_xlabel("Gate value")
        ax.legend()

    plt.tight_layout()
    plt.savefig("gate_distributions.png")
    print("Saved: gate_distributions.png")

# Main Execution

def run():
    train_loader, test_loader = load_data()

    lambdas = [1e-5, 5e-5, 1e-4]
    epochs = 40

    results = []

    for lam in lambdas:
        print(f"\n{'='*50}")
        print(f"Lambda = {lam}")
        print(f"{'='*50}")

        model = SparseMLP().to(DEVICE)
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

        for ep in range(1, epochs + 1):
            loss, train_acc = train_epoch(model, train_loader, optimizer, lam, ep, epochs)
            test_acc = evaluate(model, test_loader)
            sparsity = model.sparsity_ratio()

            print(f"Ep {ep:02d} | Loss {loss:.3f} | Train {train_acc*100:.1f}% | "
                  f"Test {test_acc*100:.1f}% | Sparsity {sparsity*100:.1f}%")

        results.append({
            "lam": lam,
            "acc": evaluate(model, test_loader),
            "sparsity": model.sparsity_ratio(),
            "gates": model.all_gate_values(),
        })

    plot_distributions(results)

# Run Script
if __name__ == "__main__":
    run()